# Uncomment the next line to define a global platform for your project
platform :ios, '16.2'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for iosApp
  pod 'Shared', :path => '../shared/'
  pod 'KMPNativeCoroutinesCombine', '0.13.1'

end
